version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 0lCB7CQhKlXLw/b3BXWXHNDOsWrDcjGemU8WcnbRU9yvjSfKK+jkEg6yd/9ufI7k
before_build:
  - nuget restore ".\Data.Generic.Cache.sln"
build:
  project: .\Data.Generic.Cache.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""test\Data.Generic.Cache.Tests\bin\$env:CONFIGURATION\Data.Generic.Cache.Tests.dll"" /noshadow" -filter:"+[Data.Generic.Cache*]*" -output:opencoverCoverage.xml

    .\packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
